spring.application.name=lexguard
spring.config.import=optional:file:.env[.properties]
spring.profiles.active=${APP_ENV:dev}


spring.datasource.url=jdbc:mysql://localhost:3306/lexguard
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:password}
spring.flyway.enabled=false

spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET:TGV4R3VhcmRTZWNyZXRLZXkyMDI2UHJvamVjdFNlY3VyaXR5S2V5MTIzNDU2}
jwt.expiration=${JWT_EXPIRATION:86400000}


logging.level.com.lexguard=INFO
logging.level.org.springframework.security=INFO
