spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/lexguard}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:password}
jwt.secret=${JWT_SECRET:TGV4R3VhcmRQcm9kU2VjcmV0S2V5MjAyNlByb2plY3RTZWN1cml0eUtleTEyMzQ1Ng==}
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}

logging.level.com.lexguard=WARN
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR
